/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.widget.jsonc --env-file=.tmp/widget-worker.env --include-runtime=false workers/widget-delivery/worker-configuration.d.ts` (hash: 4244ca629f6011b823f8b11dd959b509)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
