/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.widget.jsonc --env-file=.tmp/widget-worker.env --include-runtime=false workers/widget-delivery/worker-configuration.d.ts` (hash: 2927cd513fea188bffa343a7b25aec8a)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	BACKEND_API_ORIGIN: "https://app.renuvex.app";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
