// Generated from the live ikas schema. Do not edit manually.
declare global {
  type CustomerEmailSubscriptionStatusesEnum = "NOT_SUBSCRIBED" | "PENDING_CONFIRMATION" | "SUBSCRIBED";

  type OrderLineItemStatusEnum = "CANCELLED" | "CANCEL_REJECTED" | "CANCEL_REQUESTED" | "DELIVERED" | "FULFILLED" | "PLANNED" | "REFUNDED" | "REFUND_REJECTED" | "REFUND_REQUESTED" | "REFUND_REQUEST_ACCEPTED" | "RETURN_DELIVERED" | "RETURN_IN_TRANSIT" | "RETURN_PARCEL_WAITING" | "RETURN_REJECTED" | "UNFULFILLED";

  type OrderPackageFulfillStatusEnum = "CANCELLED" | "CANCEL_REJECTED" | "CANCEL_REQUESTED" | "DELIVERED" | "ERROR" | "FULFILLED" | "PLANNED" | "READY_FOR_PICK_UP" | "READY_FOR_SHIPMENT" | "REFUNDED" | "REFUND_REJECTED" | "REFUND_REQUESTED" | "REFUND_REQUEST_ACCEPTED" | "RETURN_DELIVERED" | "RETURN_IN_TRANSIT" | "RETURN_PARCEL_WAITING" | "RETURN_REJECTED" | "UNABLE_TO_DELIVER";

  type OrderPackageStatusEnum = "CANCELLED" | "CANCEL_REJECTED" | "CANCEL_REQUESTED" | "DELIVERED" | "FULFILLED" | "PARTIALLY_CANCELLED" | "PARTIALLY_DELIVERED" | "PARTIALLY_FULFILLED" | "PARTIALLY_READY_FOR_SHIPMENT" | "PARTIALLY_REFUNDED" | "PLANNED" | "READY_FOR_PICK_UP" | "READY_FOR_SHIPMENT" | "REFUNDED" | "REFUND_REJECTED" | "REFUND_REQUESTED" | "REFUND_REQUEST_ACCEPTED" | "RETURN_DELIVERED" | "RETURN_IN_TRANSIT" | "RETURN_PARCEL_WAITING" | "RETURN_REJECTED" | "UNABLE_TO_DELIVER" | "UNFULFILLED";

  type OrderPaymentStatusEnum = "FAILED" | "OVER_PAID" | "PAID" | "PARTIALLY_PAID" | "REFUNDED" | "WAITING";

  type OrderShippingMethodEnum = "CLICK_AND_COLLECT" | "DIGITAL_DELIVERY" | "NO_SHIPMENT" | "SHIPMENT";

  type OrderStatusEnum = "CANCELLED" | "CREATED" | "DRAFT" | "PARTIALLY_CANCELLED" | "PARTIALLY_REFUNDED" | "REFUNDED" | "REFUND_REJECTED" | "REFUND_REQUESTED" | "WAITING_UPSELL_ACTION";
}

export {};
