function previewImage(fileName) {
  return window.location.origin + '/preview-assets/' + fileName;
}

function reviewRows() {
  return [
    {
      id: 'preview-review-1',
      productId: 'preview-product',
      storeId: 'preview-store',
      author: 'Ayşe K.',
      rating: 5,
      title: 'Beklentimin üzerinde',
      comment: 'Ürün kalitesi ve kullanım deneyimi beklentimi karşıladı. Paketleme de oldukça özenliydi.',
      status: 'approved',
      isVerifiedPurchase: true,
      images: [
        previewImage('review-photo-1.svg'),
        previewImage('review-photo-2.svg'),
      ],
      merchantReply: 'Değerlendirmeniz için teşekkür ederiz.',
      createdAt: '2026-07-18T10:00:00.000Z',
    },
    {
      id: 'preview-review-2',
      productId: 'preview-product',
      storeId: 'preview-store',
      author: 'Mehmet T.',
      rating: 4,
      title: 'Memnun kaldım',
      comment: 'Genel olarak başarılı bir ürün. Kısa sürede elime ulaştı.',
      status: 'approved',
      isVerifiedPurchase: false,
      images: [previewImage('review-photo-3.svg')],
      merchantReply: null,
      createdAt: '2026-07-15T12:00:00.000Z',
    },
    {
      id: 'preview-review-3',
      productId: 'preview-product',
      storeId: 'preview-store',
      author: 'Zeynep A.',
      rating: 5,
      title: 'Tam aradığım ürün',
      comment: 'Görseldekiyle uyumlu ve kullanımı rahat.',
      status: 'approved',
      isVerifiedPurchase: true,
      images: [],
      merchantReply: null,
      createdAt: '2026-07-11T09:30:00.000Z',
    },
    {
      id: 'preview-review-4',
      productId: 'preview-product',
      storeId: 'preview-store',
      author: 'Can B.',
      rating: 5,
      title: 'Başarılı',
      comment: 'Fiyat ve performans dengesi iyi.',
      status: 'approved',
      isVerifiedPurchase: true,
      images: [],
      merchantReply: null,
      createdAt: '2026-07-07T14:15:00.000Z',
    },
    {
      id: 'preview-review-5',
      productId: 'preview-product',
      storeId: 'preview-store',
      author: 'Elif Y.',
      rating: 4,
      title: 'Tavsiye ederim',
      comment: 'Küçük detaylar dışında memnun kaldım.',
      status: 'approved',
      isVerifiedPurchase: false,
      images: [],
      merchantReply: null,
      createdAt: '2026-07-03T16:45:00.000Z',
    },
    {
      id: 'preview-review-6',
      productId: 'preview-product',
      storeId: 'preview-store',
      author: 'Deniz K.',
      rating: 5,
      title: 'Çok iyi',
      comment: 'Uzun süredir kullanıyorum ve sorun yaşamadım.',
      status: 'approved',
      isVerifiedPurchase: true,
      images: [],
      merchantReply: null,
      createdAt: '2026-06-28T11:20:00.000Z',
    },
    {
      id: 'preview-review-7',
      productId: 'preview-product',
      storeId: 'preview-store',
      author: 'Selin R.',
      rating: 3,
      title: 'Ortalama',
      comment: 'Beklentimi tamamen karşılamadı ancak kullanışlı.',
      status: 'approved',
      isVerifiedPurchase: false,
      images: [],
      merchantReply: null,
      createdAt: '2026-06-22T08:00:00.000Z',
    },
    {
      id: 'preview-review-8',
      productId: 'preview-product',
      storeId: 'preview-store',
      author: 'Burak N.',
      rating: 5,
      title: 'Kesinlikle tavsiye',
      comment: 'Malzeme kalitesi ve görünümü başarılı.',
      status: 'approved',
      isVerifiedPurchase: true,
      images: [],
      merchantReply: null,
      createdAt: '2026-06-17T17:30:00.000Z',
    },
  ];
}

export function createPreviewReviewPages() {
  var rows = reviewRows();
  return {
    1: {
      data: {
        reviews: rows.slice(0, 5),
        totalCount: 8,
        allCount: 8,
        page: 1,
        totalPages: 2,
        hasMore: true,
        ratingCounts: [0, 0, 1, 2, 5],
        avgRating: '4.5',
        mediaReviewCount: 3,
        photoReviewCount: 3,
      },
    },
    2: {
      data: {
        reviews: rows.slice(5),
        totalCount: 8,
        allCount: 8,
        page: 2,
        totalPages: 2,
        hasMore: false,
        ratingCounts: [0, 0, 1, 2, 5],
        avgRating: '4.5',
        mediaReviewCount: 3,
        photoReviewCount: 3,
      },
    },
  };
}

export var PREVIEW_LISTING_RATINGS = [
  { slug: 'preview-shirt', name: 'Klasik Gömlek', avg: '4.8', count: 42, productId: 'preview-listing-1' },
  { slug: 'preview-shorts', name: 'Premium Şort', avg: '4.5', count: 18, productId: 'preview-listing-2' },
  { slug: 'preview-jacket', name: 'Hafif Ceket', avg: '4.2', count: 7, productId: 'preview-listing-3' },
];
